{% set name = "pschism" %}
{% set version = "5.10.1" %}
{% set build = 0 %}
{% set mpi_prefix = "mpi_" + mpi %}
{% set build_pin = mpi_prefix + '_*' %}

{# Get build string #}
{% if GIT_BUILD_STR and GIT_BUILD_STR.startswith("0_") %}
  {% set build_string = "" %}
{% else %}
  {% set build_string = GIT_BUILD_STR + "_" %}
{% endif %}

package:
  name: {{ name|lower }}      #-{{ TVD_LIM|lower }}
  version: {{ GIT_DESCRIBE_TAG | replace('-', '_') }}

source:
  git_url: ../
  git_rev: HEAD

build:
  number: {{ build }}
  skip: true #[win]
  merge_build_host: true
  string: {{ build_string }}{{ mpi_prefix }}_py{{ python }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
  host:
    - python {{ python }}
    - git
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - cmake
    - sed
    - {{ mpi }}
    - {{ mpi }}-mpifort
    - {{ mpi }}-mpicc
    - {{ mpi }}-mpicxx
    - llvm-openmp
    - parmetis
    - metis
    - netcdf-fortran * {{ mpi_prefix }}_*
    - libgfortran5
  run:
    - python {{ python }}
    - {{ mpi }}
    - llvm-openmp
    - parmetis
    - metis
    - netcdf-fortran * {{ mpi_prefix }}_*
test:
  commands:
    - schism -v

about:
  home: https://github.com/schism-dev/schism
  license: Apache-2
  license_family: APACHE
  license_file: LICENSE
  summary: 'Semi-implicit Cross-scale Hydroscience Integrated System Model'

extra:
  recipe-maintainers:
    - brey
